\chapter{Linear Models}

\section{First linear model}

<<>>=
vs <- mincLm(jacobians ~ Genotype, gf)
vs
mincWriteVolume(vs, "simple-lm.mnc", "Genotype+")
@ 

mincLm is the command to run linear models in RMINC. Its basic use is
to provide a formula (same syntax as the R \texttt{lm} command) with
the left side containing the filenames, the right side the variables
to be regressed. The output of mincLm depends on the formula. There
will always be a column of F-statistics, representing the significance
of the entire model. Then there is one column for each of the terms in
the mode. The above linear model, relating the Jacobian determinant to
Genotype, will thus have three columns:

\begin{description}
\item[F-statistic] representing the significance of the entire model.
\item[(Intercept)] the intercept term - this term is rarely
  interesting, as it tests for whether the intercept is 0. There's no
  reason to believe it should be in most cases, so this value will be
  highly significant but meaningless.
\item[Genotype+] the term testing whether the ``+'' level of the
  Genotype factor is significant. In this case this term is the most
  interesting and therefore the one written to file.
\end{description}

The output is placed into a variable that can be written to file in
the same way as described in the descriptive statistics section. 


\section{Plotting voxels}

<<>>=
options(show.signif.stars=FALSE)
voxel <- mincGetVoxel(gf$jacobians,0,0,0)
summary(lm(voxel ~ Genotype, gf))
vs[1,]
@ 

The code above does the following: it gets the voxel from coordinates
0,0,0 for all subjects, then computes a linear model relating that
voxel to Genotype using standard R functions. Lastly it prints the
results from that same voxel as computed by \texttt{mincLm}. This
helps illustrate what the output of \texttt{mincLm} stores: the
F-statistic is the same as can be found in the last line of the
summary command, and the t-statistics for the Intercept and Genotype
column can be found under "t-value" when using standard R functions.

\texttt{mincGetVoxel} needs three coordinates, given in voxel space in
the same order as stored in the file. Just printing the voxel will
show the corresponding world coordinates:

<<>>=
voxel
@ 

If the coordinates are specified in world coordinates then
\texttt{mincGetWorldVoxel} is what you want - it also takes three
coordinates, this time in world space in xspace,yspace,zspace order:

<<>>=
world.voxel <- mincGetWorldVoxel(gf$jacobians, -6.27, -8.19, -4.2)
world.voxel
@ 

\section{Using subsets}

It is quite common to want to run a linear model on only a subset of
the data. This can be quite easily accomplished in \texttt{mincLm}
using an extra subsetting specification:

<<>>=
vs <- mincLm(jacobians ~ Genotype, gf, Sex=="M")
vs
@ 

This is the same linear model command as executed above, but this time
using only the male mice for the computation.

\section{Multiple Comparisons}

The example below illustrates the entire process involved in going
running a linear model and correcting for multiple comparisons using
the False Discovery Rate:

<<>>=
vs <- mincLm(jacobians ~ Sex * Genotype, gf)
qvals <- mincFDR(vs, mask="mask.mnc")
qvals
mincWriteVolume(qvals, "Genotype-FDR.mnc", "Genotype+")
@ 

The first command computes an ANOCA using \texttt{mincLm}. The results
are then passed on to \texttt{mincFDR}, which computes the False
Discovery Rate threshold separately for each of the terms in the
linear model. Only results from within the mask specified as an
optional argument to \texttt{mincFDR} are considered. The thresholds
detected at different levels (0.01, 0.05, 0.10, 0.15, and 0.20) are
then printed out. The ``Genotype+'' column is then written to file.



