// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_minc_apply
List rcpp_minc_apply(CharacterVector filenames, bool use_mask, CharacterVector mask, double mask_lower_val, double mask_upper_val, RObject value_for_mask, bool filter_masked, NumericVector slab_sizes, Function fun, List args);
RcppExport SEXP RMINC_rcpp_minc_apply(SEXP filenamesSEXP, SEXP use_maskSEXP, SEXP maskSEXP, SEXP mask_lower_valSEXP, SEXP mask_upper_valSEXP, SEXP value_for_maskSEXP, SEXP filter_maskedSEXP, SEXP slab_sizesSEXP, SEXP funSEXP, SEXP argsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type filenames(filenamesSEXP);
    Rcpp::traits::input_parameter< bool >::type use_mask(use_maskSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type mask(maskSEXP);
    Rcpp::traits::input_parameter< double >::type mask_lower_val(mask_lower_valSEXP);
    Rcpp::traits::input_parameter< double >::type mask_upper_val(mask_upper_valSEXP);
    Rcpp::traits::input_parameter< RObject >::type value_for_mask(value_for_maskSEXP);
    Rcpp::traits::input_parameter< bool >::type filter_masked(filter_maskedSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type slab_sizes(slab_sizesSEXP);
    Rcpp::traits::input_parameter< Function >::type fun(funSEXP);
    Rcpp::traits::input_parameter< List >::type args(argsSEXP);
    __result = Rcpp::wrap(rcpp_minc_apply(filenames, use_mask, mask, mask_lower_val, mask_upper_val, value_for_mask, filter_masked, slab_sizes, fun, args));
    return __result;
END_RCPP
}
