# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

anat_summary <- function(filenames, atlas, method) {
    .Call('RMINC_anat_summary', PACKAGE = 'RMINC', filenames, atlas, method)
}

count_labels <- function(filenames) {
    .Call('RMINC_count_labels', PACKAGE = 'RMINC', filenames)
}

rcpp_minc_apply <- function(filenames, use_mask, mask, mask_lower_val, mask_upper_val, value_for_mask, filter_masked, slab_sizes, fun, args) {
    .Call('RMINC_rcpp_minc_apply', PACKAGE = 'RMINC', filenames, use_mask, mask, mask_lower_val, mask_upper_val, value_for_mask, filter_masked, slab_sizes, fun, args)
}

